---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: k8s-test
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: gcr.io/steady-grid-281506/helloworld:1.0.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb
  namespace: k8s-test
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
    - port: 10000
      targetPort: 8080
  selector:
    app: hello-world