---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: k8s-test
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: <YOUR IMAGE PATH HERE>
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-deployment-lb
  labels:
    app: devops
    tier: frontend-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: devops
    tier: frontend